### ISSUE TITLE
 $config['url_mode'] = 0 is not working

### ISSUE THREAD

**Issue by domsie** [Athlon1600/php-proxy-app#19]
Hi,

i have set 
$config['url_mode'] = 0;
in the config.php.

Nevertheless, the URL param 'q' always by Base64 encoded / decoded, so that you can not pass the URL in plain text. Mean e.g.: ?q=google.de  
Before I adapting your otherwise 100% working code I wanted to ask if I did something wrong with the configuration?

**Comment by Athlon1600** [comment]
It's actually working as it should. url_mode = 0, as it says in the description, simply means no ENCRYPTION. Base64 is not encryption. It's just a "safe" way of passing long and complicated URLs from one page to another. URL that's wrapped in Base64 does not get encrypted, so that's all that option 0 means.  
To do what you want, I would need to make up another setting like url_mode = 9 that lets you do exactly that. So this will probably be included in the next update. Give me a day or two and this will be added.

**Comment by domsie** [comment]
Hi,
yes, you are right.
url_mode = 9 is a very good idea.
Many thanks for your effort
