### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by mongoload** [Athlon1600/php-proxy-app#54]
Hi, 

I'm just a beginner with this kind of things and I hope you could help me. I have successfully deployed your proxy script on my VPS. Just yesterday, it doesn't work anymore with HTTP error 500.

I have destroyed the droplet and start fresh and used your one-click install and with still the same issue.

Hope you could help me. Thank you in advance!

**Comment by Athlon1600** [comment]
Yup, I'm aware of this issue. This is the issue:
https://github.com/Athlon1600/php-proxy/issues/60

**Comment by mongoload** [comment]
Hello, thank you for acknowledging the issue. May I know if the solution will be automatic and nothing to do/change in our config? thank you!

**Comment by Athlon1600** [comment]
Not sure. Is your system setup to automatically update php-proxy package via "composer update"?

**Comment by mongoload** [comment]
I think if my config had the problem without me changing anything, then it automatically updates right? 

By the way, why does unblockvideos.com works even though it is based on PHP-proxy? Anyway, thanks for this proxy and looking forward on your fix

**Comment by Athlon1600** [comment]
It's automatically updated if you have a cron-job or something similar that runs periodically and calls the command "composer update" inside a directory where php-proxy-app is installed. If you installed php-proxy-app via this installer:  
https://github.com/Athlon1600/php-proxy-installer  
  
then that periodic check is automatically added to your list of cron-jobs. Either way, it's not going to matter in a few days because I plan on fixing it today or tomorrow.

**Comment by zarzen** [comment]
@Athlon1600 Hi, so older version will be fine? 
I hope to deploy one

**Comment by zarzen** [comment]
Is this caused by PHP7? 
The default version installed by ubuntu16.04 is PHP7.

**Comment by Athlon1600** [comment]
Do a "composer update" now and it should work with this new release:  
https://github.com/Athlon1600/php-proxy/commit/12584d6892779c719d26f79bf464e7d9a2b48f88

**Comment by mongoload** [comment]
Alright, it is now working! 

Thank you so much!
