### ISSUE TITLE
Fatal Error - Please Help

### ISSUE THREAD

**Issue by sam-gurdus** [Athlon1600/php-proxy-app#61]
After adding the YouTube plugin to the plugins folder, going to my website, and typing in 'youtube.com,' I got this error: Fatal error: Uncaught Error: Class 'YoutubePlugin' not found in /storage/ssd3/627/2620627/public_html/index.php:89 Stack trace: #0 {main} thrown in /storage/ssd3/627/2620627/public_html/index.php on line 89

**Comment by Athlon1600** [comment]
which YouTube plugin are you added to your plugins folder?

**Comment by samrocks9** [comment]
The default one, I believe. Also while you're here, I was wondering why some websites don't work correctly using the proxy. Does it not support javascript or something? Some websites' buttons don't seem to work.

**Comment by Athlon1600** [comment]
Where are you getting this default plugin from? Here?  
https://github.com/Athlon1600/php-proxy-plugin-cache  
  
> Does it not support javascript or something? Some websites' buttons don't seem to work.

That depends on just how complex the site is, because every web-proxy has to "proxify" all parts of the page - images, links, etc...  that tends to break some of javascript's logic on that page. That is just how it is with all web proxies.

**Comment by samrocks9** [comment]
No, I’m not

On Sat, Sep 16, 2017 at 5:04 PM Athlon1600

<
mailto:Athlon1600 <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Where are you getting this default plugin from? Here?
https://github.com/Athlon1600/php-proxy-plugin-cache

Does it not support javascript or something? Some websites' buttons don't seem to work.

That depends on just how complex the site is, because every web-proxy has to "proxify" all parts of the page - images, links, etc... that tends to break some of javascript's logic on that page. That is just how it is with all web proxies.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/Athlon1600/php-proxy-app/issues/61#issuecomment-330002648
, or

**Comment by Athlon1600** [comment]
Paste me the contents of that plugin here then.

**Comment by samrocks9** [comment]
This is where I got it, didn't you make it? https://github.com/Athlon1600/php-proxy-plugin-bundle

**Comment by Athlon1600** [comment]
Yes, but that is meant to be installed with composer. I think there is an issue with namespaces here. Removing "namespace Proxy\Plugin;" from YoutubePlugin.php should make it all work.

**Comment by samrocks9** [comment]
I'm a little confused. What is the process for installing just the YouTube plugin and fixing that issue?

**Comment by Athlon1600** [comment]
All of those plugins are installed by default. It's up to you to decide which ones you want enabled or not. Look here:  
https://github.com/Athlon1600/php-proxy-app/blob/master/config.php#L23  
  
Every plugin below "// site specific plugins below" line comes from "php-proxy-plugin-bundle" package. If you don't want any of them except for youtube, then remove them from that array.

**Comment by samrocks9** [comment]
Wait so I don't even need to download the plugin package thing?

**Comment by samrocks9** [comment]
Also, I was wondering if there was any way to modify the script to open the
proxified page in a new tab, instead of just redirecting. I am trying to
use the proxy site in an iframe that is only like 125 px tall, so not
enough room to display the proxified page, just the url bar and go button.

**Comment by Athlon1600** [comment]
> Wait so I don't even need to download the plugin package thing?

It's downloaded and installed automatically if you do it via composer. Check the "require" block:  
https://github.com/Athlon1600/php-proxy-app/blob/master/composer.json  
  
I'm pretty sure it's the same if you use pre-installed version of php-proxy:  
https://www.php-proxy.com/download/php-proxy.zip

**Comment by samrocks9** [comment]
Also, I was wondering if there was any way to modify the script to open the proxified page in a new tab, instead of just redirecting. I am trying to use the proxy site in an iframe that is only like 125 px tall, so not enough room to display the proxified page, just the url bar and go button.

**Comment by Athlon1600** [comment]
Something like this would probably work:
Go to php-proxy-app's config.php file and change url_mode parameter to 0:  
```php
$config['url_mode'] = 0;
```

that way you can link directly to any proxified URL like this:  
your-site.com/php-proxy-app/index.php?q=http://www.yahoo.com

Then, inside your iframe form, make your form open a window upon submit that shows the proxified page of whatever site user put inside the URL field of that form. Like this:

```javascript
$(your_form).onsubmit(function(){
    var url = $("#url").val();
    var proxy_url = 'your-site.com/php-proxy-app/index.php?q=' + url;
    window.open(proxy_url, '_blank');
    return false;
});
```

**Comment by Athlon1600** [comment]
I assumed my fix solved your issue.
